apiVersion: apps/v1
kind: Deployment
metadata:
  name: noudyba-app
  labels:
    app: noudyba-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noudyba-app
  template:
    metadata:
      labels:
        app: noudyba-app
    spec:
      containers:
        - name: noudyba-app
          image: kennegervais/noudyba-app:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8050

---
apiVersion: v1
kind: Service
metadata:
  name: noudyba-app-svc
spec:
  ports:
    - targetPort: 8050
      port: 80
  selector:
    app: noudyba-app
